name: Kickbase Bot Execution

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'  # Laufen alle 8 Stunden

jobs:
  run-bot:
    runs-runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 google-genai

      - name: Run Kickbase bot
        env:
          KB_EMAIL: ${{ secrets.KB_EMAIL }}
          KB_PASSWORD: ${{ secrets.KB_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
